# SPDX-FileCopyrightText: 2026 Deliverance Enterprises
#
# SPDX-License-Identifier: MIT

services:
  turtlebot-ros2-gazebo:
    build:
      context: ../..
      dockerfile: docker/ros2_gazebo/Dockerfile
    image: deliverance/turtlebot-connector-ros2-gazebo:humble
    container_name: turtlebot-connector-ros2-gazebo
    environment:
      - TURTLEBOT3_MODEL=${TURTLEBOT3_MODEL:-waffle_pi}
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-42}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      - RESOLUTION=${RESOLUTION:-1280x800}
    volumes:
      - ../..:/workspace/turtlebot_connector:rw
    ports:
      - "6080:80"
      - "5900:5900"
    shm_size: "2gb"
    stdin_open: true
    tty: true
